Deepcopy option (1st step towards #47)
pyscaffold/configupdater pull request #48
Opened 2021-07-06 13:09 UTC by abravalheri

This is the first step to fix #47, by implementing `__deepcopy__` on `Option`.

I tried to make use of the inheritance chain (this way `Comment` and `Space` would also be fixed), but since different subclasses have different arguments for `__init__`, I had to add some indirection and an auxiliary `_intantiate_copy` to make overwrites possible.

Moreover this PR also include a fix that allows calling `optionxform` on detached objects. It was very tricky to add a test case without fixing this issue.

2021-07-06 18:56 UTC, FlorianWilhelm requested changes
I am not so sure if having `optionxform` in `Option` and `Section` is such a good idea. See `ConfigParser`'s docs.

2021-07-06 18:56 UTC, FlorianWilhelm commented on src/configupdater/option.py
> +
The problem with having optionxform not on the document level is that a user would need to overwrite this method in `Block`, `Section`, etc. See the docs of ConfigParser why they choose this hook for the user.

2021-07-06 19:14 UTC, abravalheri commented
Hi @FlorianWilhelm, thank you very much for the review.

Yeah, I see the `optionxform` topic is a bit complicated... In the changes I am proposing in this PR, what is actually happening is that the call for `optionxform` is propagated until the top level element, which still allows the configuration of the `optionxform` as described in the ConfigParser documentation.

So for example, if we call that method on `option`, it will propagate the call to `section` that will in turn propagate the call to the `ConfigUpdater` object. The local implementation is just a fallback in the case either section or options are in a detached state.

The original intention was not to touch this method, but when running the tests I noticed it is very tricky not to. For example, we cannot check if an option already exists in a detached section, we cannot call `.key` on a detached option and so on... If we try, there is a `NotAttachedError`.

2021-07-08 16:29 UTC, FlorianWilhelm commented
Thanks for the explanations @abravalheri. It really gets tricky after a while but as long as a detached section/option always raises an exception this should be fine. So looks good to me. Feel free to merge.

2021-07-08 17:26 UTC, abravalheri commented
Hi @FlorianWilhelm, thanks for looking into this again.

I am not sure if I understood the  `as long as a detached section/option always raises an exception` part...
With the proposed solution, there will be an exception every time we try to use `.container` in a block, e.g., when using `.add_after` or `.next_block`. But this PR would result in no error being raised if `.container` is just being accessed for calling `optionxform`, since the PR provides a fallback implementation.

2021-07-10 14:52 UTC, merged